name: CI

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

# cancel in progress when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.1
      - name: Download deps
        run: go mod download
      - name: Vet
        run: go vet ./...
      - name: Test
        # there's no concurrency in here - so we don't need the -race flag
        run: go test -coverprofile=coverage.txt ./...
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.1
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.11.4