name: CI

on:
  push:
    branches: [ main ]

# cancel in progress when a new commit is pushed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 1.26.1
      - name: Download deps
        run: go mod download
      - name: Vet
        run: go vet ./...
      - name: Test
        run: go test -race -coverprofile=coverage.txt -covermode=atomic ./...